# Full chart reference available at https://github.com/bitnami/charts/tree/master/bitnami/external-dns

## DNS provider where the DNS records will be created.
provider: aws

## AWS configuration to be set via arguments/env. variables
##
aws:
  region: "${region}"

## ServiceAccount parameters
## https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
##
serviceAccount:
  create: true
  ## Service Account for pods
  ##
  name: "external-dns"
  ## Annotations for the Service Account
  ##
  annotations:
    eks.amazonaws.com/role-arn: "${aws_role_arn}"
